# Generated by Django 2.0 on 2018-01-24 12:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('detail_page', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='课程详情页')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('state', models.IntegerField(choices=[(1, '待完成'), (2, '已完成'), (3, '待改期'), (4, '已改期')], default=1)),
                ('remark', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete='SET_NULL', to='course.Course')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
                'db_table': 'course_schedule',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('parentName', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, '待完成'), (2, '已完成'), (3, '待改期'), (4, '已改期')], default=1)),
                ('remark', models.TextField()),
                ('course', models.ForeignKey(on_delete='SET_NULL', to='course.Course')),
            ],
            options={
                'verbose_name': '申请表',
                'verbose_name_plural': '申请表',
                'db_table': 'enroll_sheet',
            },
        ),
    ]
